# Generated by Django 5.0.4 on 2024-06-04 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, null=True)),
                ('categorie', models.CharField(max_length=50, null=True)),
                ('prix', models.FloatField(max_length=10, null=True)),
            ],
        ),
    ]
