# Generated by Django 5.0.4 on 2024-06-04 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='produit',
            name='categorie',
            field=models.ForeignKey(choices=[('Laitier', 'Laitier'), ('Viande', 'Viande'), ('Tech', 'Tech')], null=True, on_delete=django.db.models.deletion.SET_NULL, to='produit.categorie'),
        ),
    ]
