# Generated by Django 5.0.4 on 2024-06-06 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0003_alter_produit_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
