# Generated by Django 5.0.4 on 2024-06-06 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0004_produit_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
