# Generated by Django 5.0.4 on 2024-06-04 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='date_creation',
        ),
        migrations.AddField(
            model_name='client',
            name='adresse',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
