# Generated by Django 5.0.4 on 2024-06-05 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_remove_client_mdp_client_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='user',
        ),
        migrations.AddField(
            model_name='client',
            name='mdp',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
