# Generated by Django 5.0.4 on 2024-06-08 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_lignedepanier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lignedepanier',
            name='quantite',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
