# Generated by Django 5.0.4 on 2024-06-05 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0003_rename_date_creation_commande_date_commande_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ligne_commande',
            name='prix',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ligne_commande',
            name='quantite',
            field=models.IntegerField(null=True),
        ),
    ]
