# Generated by Django 5.0.4 on 2024-06-05 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0004_alter_ligne_commande_prix_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='quantite',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='Ligne_commande',
        ),
    ]
