# Generated by Django 5.0.4 on 2024-06-05 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0005_commande_quantite_delete_ligne_commande'),
        ('produit', '0003_alter_produit_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='produit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='produit.produit'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='cout_commande',
            field=models.IntegerField(max_length=10, null=True),
        ),
    ]
