# Generated by Django 5.0.4 on 2024-06-06 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_panier'),
        ('commande', '0006_commande_produit_alter_commande_cout_commande'),
        ('produit', '0004_produit_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='cout_commande',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='quantite',
        ),
        migrations.CreateModel(
            name='LigneDeCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('panier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='client.panier')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produit.produit')),
            ],
        ),
        migrations.AddField(
            model_name='commande',
            name='lignes',
            field=models.ManyToManyField(to='commande.lignedecommande'),
        ),
    ]
