# Generated by Django 5.0.4 on 2024-06-06 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0007_remove_commande_cout_commande_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='produit',
        ),
    ]
