# Generated by Django 5.0.4 on 2024-06-07 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0008_remove_commande_produit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='lignes',
        ),
        migrations.RemoveField(
            model_name='lignedecommande',
            name='panier',
        ),
        migrations.AddField(
            model_name='lignedecommande',
            name='commande',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='commande.commande'),
        ),
    ]
