# Generated by Django 5.0.4 on 2024-06-08 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0010_livraison_remove_commande_date_livraison_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livraison',
            name='commande',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='commande.commande'),
        ),
    ]
